"""empty message

Revision ID: 838e9dcf1289
Revises: 58116952eb5d
Create Date: 2024-04-08 02:58:32.865913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '838e9dcf1289'
down_revision = '58116952eb5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personaje', schema=None) as batch_op:
        batch_op.add_column(sa.Column('especie', sa.String(length=250), nullable=True))
        batch_op.drop_column('email')
        batch_op.drop_column('adress')

    with op.batch_alter_table('planeta', schema=None) as batch_op:
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planeta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.VARCHAR(length=250), autoincrement=False, nullable=False))

    with op.batch_alter_table('personaje', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adress', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.drop_column('especie')

    # ### end Alembic commands ###
