"""empty message

Revision ID: 8f0cc5406eed
Revises: 838e9dcf1289
Create Date: 2024-04-08 03:05:49.407966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f0cc5406eed'
down_revision = '838e9dcf1289'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personaje', schema=None) as batch_op:
        batch_op.drop_column('especie')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personaje', schema=None) as batch_op:
        batch_op.add_column(sa.Column('especie', sa.VARCHAR(length=250), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
